- name: nginx install and run
  hosts: all #by changing this to "all' it will connect to all the servers  returned by dynamic inventory
  become: yes #to give sudo access add this line, take sudo access
  serial: 3
  tasks:
  - name: install nginx
    ansible.builtin.package:  #it is an heterogenous module that can work for all distributions. By giving like this ansible-server understands the server to which it is going to connect to and perform respective dnf command in background
      name: nginx
      state: present  #if you want remove change staate as "absent"


  - name: start/Run nginx service
    ansible.builtin.service:
      name: nginx
      state: started

  - name: enabling the service
    ansible.builtin.service:
      name: nginx
      state: enabled